# Generated by Django 2.2.3 on 2019-07-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=255, verbose_name='Agencia')),
                ('nome_banco', models.CharField(default='LiraBank', max_length=255, null=True, verbose_name='Nome do banco')),
                ('numero_conta', models.CharField(max_length=255, verbose_name='Numero da conta')),
                ('saldo', models.FloatField(default=0.0)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pessoa')),
            ],
        ),
    ]
